### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by quangpro1610** [kshetline/ligatures-limited#16]
- Issue Type: `Performance`
- Extension Name: `ligatures-limited`
- Extension Version: `1.3.3`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.47.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Quang\kshetline.ligatures-limited-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kshetline** [comment]
Your attachment doesn't seem to have worked. You'll have to send it again.

Also, can you tell me if there was any noticeable problem for you as a user, like a slow or unresponsive editor, or is the only problem that an error or warning was logged?

**Comment by kshetline** [comment]
Closing because of lack of response.
