### ISSUE TITLE
Ligatures are not being disabled in vscode 1.49

### ISSUE THREAD

**Issue by BenLanglois** [kshetline/ligatures-limited#19]
## Description

Upgrading to vscode version 1.49 (August 2020) causes ligatures to not be disabled by this extension when the "selection mode" setting is set to cursor, line, or selection. I downgraded to vscode version 1.48 (July 2020) and ligatures are disabled as expected.

## System Info

- Ligatures Limited v1.3.4
- macOS 10.14.6

**Comment by BenLanglois** [comment]
I also submitted a similar issue in the disable ligatures extension: https://github.com/CoenraadS/vscode-Disable-Ligatures/issues/7

**Comment by kshetline** [comment]
That's useful to know this also problem now exists in the CoenraddS code too -- that narrows the problem down to the trick I borrowed from that code for breaking up ligatures.

Thank you for reporting this... I've mostly been using IntelliJ IDEA these days, not VSCode, and wouldn't have noticed for a while!

**Comment by kshetline** [comment]
I found a fix, but it does involve a small compromise. Suppressed ligatures will now always be in a non-bold font. That should rarely be a problem anyway (most themes don't use bold anyway), but perhaps in the future I can remove that limitation. The central issue is that VSCode doesn't provide any direct character-by-character access to where ligatures fonts are used, so it requires a styling trick to suppress ligatures. The old trick doesn't work any more, so a new trick was needed.

**Comment by kshetline** [comment]
Later today I found a better trick that doesn't have any bold font limitation.
