### ISSUE TITLE
fi ligatures not disabled in VScode 1.53

### ISSUE THREAD

**Issue by pauliharman** [kshetline/ligatures-limited#24]
The fi family of ligatures are not disabled in the latest VScode at the time of writing (1.53.0)

I'm not sure if this is the same issue as https://github.com/microsoft/vscode/issues/106596

**Comment by kshetline** [comment]
Is this only with a particular ligature font? I've updated to VSCode 1.53.0, and I'm not seeing a problem when using Fira Code.

**Comment by kshetline** [comment]
That old bug #106596 was caused by an update of VSCode back in September that caused the old technique I had used for breaking apart ligatures, borrowed from Disable Ligatures, to fail. I came up with a new trick using hair spaces which has since then remained working. That fix has been in since 2020-09-14.

**Comment by kshetline** [comment]
I tried the Iosevka font, and saw no problems with that either. By the way, there are single-codepoint Unicode ligatures for ﬀ, ﬁ, ﬂ, ﬃ, and ﬄ -- if you use those, Ligatures Limited will have no effect on them. It only breaks apart multi-codepoint ligatures which are blended into single glyphs via font rendering.

**Comment by pauliharman** [comment]
Sorry for the delay in response here - I didn't get the notifications.
I'm using a vanilla fresh install of VScode 1.53.2, on a MacBook running Catalina 10.15.7 (in case that makes a difference). I'm using Fira Code. The document I'm looking at includes words like "final" in standard UTF8 encoding - not using the codepoint for "fi" - but the "fi" of "final" is still being squashed into the corresponding ligature.

**Comment by kshetline** [comment]
That seems very odd, since afaik Fira Code doesn't even have the fi ligature. Are you sure your font wasn't accidentally changed to Menlo, which does have those ligatures?

At an rate, this addition to your settings.json should help:

`"ligaturesLimited.ligatures": "- ff fi fl ffi ffl"`

**Comment by pauliharman** [comment]
> Are you sure your font wasn't accidentally changed to Menlo

Oh. Looks like that is exactly what happened, and I hadn't noticed. Not sure what caused that to happen. Thanks for the assistance, and apologies for suggesting it was your awesome extension that was at fault.
