### ISSUE TITLE
Add /= from Ada

### ISSUE THREAD

**Issue by Lucretia** [kshetline/ligatures-limited#25]
In Ada ```/=``` is the equivalent to ```!=``` in C++, i.e. not equals and should render using the same glyph, a la ```=/=```, but as a single character.

**Comment by kshetline** [comment]
You'll have to take that up with the creator of the ligature font that you're using. All my plugin can do is allow the ligatures that exist in the font to be formed, or break them apart. It can't change the ligatures into different ligatures.

I know the Fira Code font allows for style variations that cause some characters and ligatures to be rendered differently. Perhaps what you need is an Ada-specific style variation.
