### ISSUE TITLE
Ligatures not working in Markdown files

### ISSUE THREAD

**Issue by ANK-dev** [kshetline/ligatures-limited#4]
* Extension version: `1.0.1`
* VS Code version: `1.45.1`
* OS version: `Microsoft Windows [Version 10.0.18363.836]`

With out-of-the-box settings, ligatures don't appear to work in Markdown (.md) files.

By editing the `settings.json` file with the following settings,

```json
"ligaturesLimited.languages": {
  "[markdown]": {
    "ligaturesByContext": {
      "text.html.markdown": {
        "ligatures": "X #"
      }
    }
  }
}
```

I am able to get ligatures to appear (`#` can be any character, as `X` alone doesn't seem to enable all ligatures). The biggest problem, however, is that ligatures do not disable when the cursor is over them; and using the `cycleSelectionMode` command results in an error pop-up that says:

>Command 'ligatures-limited: Cycle through the five modes of
>disabling ligatures by selection: by settings, off, cursor, line, full
>selection' resulted in an error (Running the contributed
>command: 'ligaturesLimited.cycleSelectionMode' failed.)`

I am not sure if this is due to an incorrect configuration of the json file, or some other bug.

**Comment by kshetline** [comment]
"text.html.markdown" is the top-level of the scope hierarchy, but (at least in this current version), it's only the most specific scope (in this case "meta.paragraph.markdown"), or sometimes the scope just one step above that, that counts for defining a context.

So this works:

```json
    "ligaturesLimited.languages": {
        "[markdown]": {
            "ligaturesByContext": {
                "meta.paragraph": {
                    "ligatures": "X #"
                }
            }
        }
    },
```
I'll update the documentation to make that more clear.

**Comment by ANK-dev** [comment]
So, should I use `"meta.paragraph"` or `"meta.paragraph.markdown"`? Using either one of them fixes the lack of ligatures; when placing the cursor over a ligature, however, it **isn't disabled**.

![image](https://user-images.githubusercontent.com/40664661/83212335-b3cb3880-a135-11ea-944c-9a20fc696102.png)

**Comment by kshetline** [comment]
It turns out that the added `#` is causing an error to be thrown, and the only reason the ligatures were displayed is that the extension wasn't doing anything at all to suppress ligatures after it crashed. I'm a bit confused why it seemed like it helped.

I'm now making sure errors in the configuration produce a visible error popup. For now, take out the `#` and see if that helps. I can get it to work now without the `#` myself. It might take the next update of the plug in (which will happen soon) to fix this.

**Comment by kshetline** [comment]
Specifically-enabled ligatures are working, in Markdown or elsewhere, now when the extension is correctly configured. I've also fixed the problem where configuration errors could crash the extension, and now those errors are reported to the user.

**Comment by ANK-dev** [comment]
It seems to be mostly working now (just using the `X`). With the font I'm using (Iosevka), ligatures like → (`->`) work correctly, and when the cursor is over the character, they get disabled; others, like ════ (`====`... long double line) don't render at all when the extension is enabled; and others, like ≠ (`!=`), appear to work randomly — working on some lines, and not in others. Maybe this is an issue with the parser.

![Image1](https://user-images.githubusercontent.com/40664661/83284679-6c838d00-a1b3-11ea-8682-7722b0643cab.png)
![Image2](https://user-images.githubusercontent.com/40664661/83284720-7907e580-a1b3-11ea-9802-267bd9fe0e30.png)
![Image3](https://user-images.githubusercontent.com/40664661/83284741-80c78a00-a1b3-11ea-9589-6b7239701020.png)

-------------------------------------------------------------------------------------------------------

Hmm, it also seems to happen with Fira Code. I'm attaching a section of the file I'm writing for further analysis.

[ligatures-limited-markdown-problem.zip](https://github.com/kshetline/ligatures-limited/files/4703126/ligatures-limited-markdown-problem.zip)

**Comment by kshetline** [comment]
`====` isn't in the list of ligatures handled by Ligatures Limited automatically, so you would have to add that. What's handled automatically is only what's in this picture:

<img src="https://shetline.com/readme/ligatures-limited/v1.0.0/ligature_set_suppressed.jpg">

If what you want is a ligature that forms for an _indefinite_ number of `=` signs in a row, I'd have to add special code handling for that. As it stands right now, `====` would be treated as `===` followed by `=`, `=====` would be treated as `===` followed by `==`, etc. If `===` and `==` are broken into separate `=` signs, then long rows of equal signs will also be treated the same way, unless I add, say `====` as a special case that means "4 or more `=`".

Does that sound like an enhancement you're looking for?

When you put backticks around a string, like this: `` `!=` ``, that's no longer the context `meta.paragraph.markdown`. That's the context `markup.inline.raw.string.markdown`. Other contexts apply for other forms of quoting, for headers, bold and italic, etc, so you'd have to enable all of those contexts that you want to see ligatures in them.

**Comment by ANK-dev** [comment]
Hmm, I see. 

>If what you want is a ligature that forms for an indefinite number of  `=` signs in a row, I'd have to add special code handling for that. As it stands right now, `====` would be treated as `===` followed by `=`, `=====` would be treated as `===` followed by `==`, etc. If  `===` and `==` are broken into separate `=` signs, then long rows of equal signs will also be treated the same way, unless I add, say `====` as a special case that means "4 or more `=`".
>
>Does that sound like an enhancement you're looking for?

Yes! The ideal case would be to support long ligatures for (an arbitrary number) of multiple `=`, multiple `-` and multiple `~`,  as is the case with Iosevka's arrow ligatures (`<===>`, `<--->`, `<~~~>`) and horizontal bar (`====`). I would be extremely grateful if this could be done!

![image1](https://user-images.githubusercontent.com/40664661/83296845-d5750000-a1c7-11ea-9fbf-4b94e9258d45.png)

![image2](https://user-images.githubusercontent.com/40664661/83297105-5a601980-a1c8-11ea-837a-467ee419f1a9.png)

![image3](https://user-images.githubusercontent.com/40664661/83297135-65b34500-a1c8-11ea-8e86-be51da97ef5c.png)

-------------------------------------------------------------------------------------------------------
 
>When you put backticks around a string, like this: `!=`, that's no longer the context meta.paragraph.markdown. That's the context markup.inline.raw.string.markdown. Other contexts apply for other forms of quoting, for headers, bold and italic, etc, so you'd have to enable all of those contexts that you want to see ligatures in them.

So I need to setup the ligatures for each context. Is there a shorthand to enable ligatures for all contexts within a markdown file?

**Comment by kshetline** [comment]
If you use Ligature Limited's "category" concept to specify a context, rather than using TextMate scope, then `text` covers almost everything, the rest being `punctuation`. So you'd just need:

```
    "ligaturesLimited.languages": {
        "markdown": {
            "ligaturesByContext": {
                "text, punctuation": {
                    "ligatures": "X"
                }
            }
        }
    },
```
...so that ligatures would essentially be fully enabled in Markdown (with the exception of other languages embedded inside markdown, like when you do this:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/24473229/83301120-11f42c00-a1c7-11ea-8779-93b585c871f1.png">

I'll think about adding the ability to completely enable or disable ligatures for specific languages too -- but that will be a new feature, not there right now.

**Comment by ANK-dev** [comment]
This works. Only thing left to add is support for long ligatures like (`=====`). Thanks!

**Comment by kshetline** [comment]
There's now an update, version 1.1.0, that supports the extra ligatures you're looking for, and simplifies enabling all ligatures for a particular language, like Markdown, like this:

```json
{
  "ligaturesLimited.languages": {
    "markdown": true
  }
}
```
